//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string ISBN { get; set; }
        public string TITLE { get; set; }
        public int YEARPUB { get; set; }
        public string StuId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Student Student { get; set; }
    }
}
